# Importra bibliotecas

In [73]:
import pandas as pd
import numpy as np
import os

## carga de cvs a df

In [74]:
""" leer el archivo de manera segura """

file = os.path.join("cereal.csv")

In [75]:
""" convertir el cvs a dataframe """
DFCereal = pd.read_csv(file)

In [76]:
""" obtner los primeros 5 registros """

DFCereal.head()

Cereal Name    Manufacturer Type  Calories  Protein (g)  Fat  \
0                  100%_Bran         Nabisco    C      70.0            4  1.0   
1          100%_Natural_Bran     Quaker Oats    C     120.0            3  5.0   
2                   All-Bran        Kelloggs    C      70.0            4  1.0   
3  All-Bran_with_Extra_Fiber        Kelloggs    C      50.0            4  NaN   
4             Almond_Delight  Ralston Purina    C     110.0            2  2.0   

   Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0   130.0           10.0    5.0     6.0            3.0      280.0   
1    15.0            2.0    8.0     8.0            3.0      135.0   
2   260.0            9.0    7.0     5.0            3.0      320.0   
3   140.0           14.0    8.0     NaN            3.0      330.0   
4   200.0            1.0   14.0     8.0            3.0        NaN   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                     25                  1.0              0.33  
1                      0                  1.0             -1.00  
2                     25                  1.0              0.33  
3                     25                  1.0              0.50  
4                     25                  1.0              0.75

In [77]:
""" ver un analisis rapoido de los datos  """

DFCereal.describe()

Calories  Protein (g)        Fat      Sodium  Dietary Fiber  \
count   72.000000    74.000000  72.000000   73.000000      69.000000   
mean   105.972222     2.500000   0.972222  160.000000       2.198551   
std     18.512251     1.088546   0.963740   85.578099       2.433739   
min     50.000000     1.000000   0.000000    0.000000       0.000000   
25%    100.000000     2.000000   0.000000  130.000000       1.000000   
50%    110.000000     2.000000   1.000000  180.000000       2.000000   
75%    110.000000     3.000000   1.000000  220.000000       3.000000   
max    160.000000     6.000000   5.000000  320.000000      14.000000   

           Carbs     Sugars  Display Shelf   Potassium  Vitamins and Minerals  \
count  70.000000  69.000000      70.000000   72.000000              74.000000   
mean   15.000000   7.246377       2.214286   95.277778              28.378378   
std     3.935163   4.244047       0.832194   69.767667              22.787104   
min     5.000000  -1.000000       1.000000   15.000000               0.000000   
25%    12.250000   3.000000       1.250000   40.000000              25.000000   
50%    15.000000   7.000000       2.000000   90.000000              25.000000   
75%    17.000000  11.000000       3.000000  116.250000              25.000000   
max    23.000000  15.000000       3.000000  330.000000             100.000000   

       Serving Size Weight  Cups per Serving  
count            74.000000         74.000000  
mean              1.027432          0.629054  
std               0.151260          0.576843  
min               0.500000         -1.000000  
25%               1.000000          0.670000  
50%               1.000000          0.750000  
75%               1.000000          1.000000  
max               1.500000          1.500000

## Renombrar las columnas

In [78]:
name_columns = {
    "Cereal Name": "Name",
    "Manufacturer": "Manuf",
    "Protein (g)": "Protein",
    "Potassium": "Potass",
    "Vitamins and Minerals": "Vitamins",
}

In [79]:
DFCereal = DFCereal.rename(columns=name_columns)

In [80]:
""" comprobar el renombrado de las columnas """

DFCereal.head()

Name           Manuf Type  Calories  Protein  Fat  \
0                  100%_Bran         Nabisco    C      70.0        4  1.0   
1          100%_Natural_Bran     Quaker Oats    C     120.0        3  5.0   
2                   All-Bran        Kelloggs    C      70.0        4  1.0   
3  All-Bran_with_Extra_Fiber        Kelloggs    C      50.0        4  NaN   
4             Almond_Delight  Ralston Purina    C     110.0        2  2.0   

   Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potass  Vitamins  \
0   130.0           10.0    5.0     6.0            3.0   280.0        25   
1    15.0            2.0    8.0     8.0            3.0   135.0         0   
2   260.0            9.0    7.0     5.0            3.0   320.0        25   
3   140.0           14.0    8.0     NaN            3.0   330.0        25   
4   200.0            1.0   14.0     8.0            3.0     NaN        25   

   Serving Size Weight  Cups per Serving  
0                  1.0              0.33  
1                  1.0             -1.00  
2                  1.0              0.33  
3                  1.0              0.50  
4                  1.0              0.75

<!--  -->

## seleccionar un subconjunto de los primeros 50 datos y columnas de necesarias para el analisis de los datos


In [81]:
DFSCereal = DFCereal.head(50)

In [82]:
DFSCereal.describe()

Calories    Protein        Fat      Sodium  Dietary Fiber      Carbs  \
count   48.000000  50.000000  48.000000   49.000000      48.000000  48.000000   
mean   109.375000   2.440000   1.145833  171.836735       2.281250  14.302083   
std     17.308988   1.052887   1.051637   69.833835       2.759714   3.932596   
min     50.000000   1.000000   0.000000    0.000000       0.000000   5.000000   
25%    100.000000   2.000000   0.000000  140.000000       1.000000  12.000000   
50%    110.000000   2.000000   1.000000  180.000000       1.500000  14.000000   
75%    120.000000   3.000000   2.000000  220.000000       3.000000  17.000000   
max    160.000000   6.000000   5.000000  290.000000      14.000000  22.000000   

          Sugars  Display Shelf      Potass    Vitamins  Serving Size Weight  \
count  48.000000      48.000000   48.000000   50.000000            50.000000   
mean    8.104167       2.312500   97.708333   27.000000             1.047400   
std     3.816201       0.748225   75.152033   15.843624             0.121702   
min     0.000000       1.000000   20.000000    0.000000             1.000000   
25%     5.000000       2.000000   40.000000   25.000000             1.000000   
50%     8.000000       2.000000   90.000000   25.000000             1.000000   
75%    11.250000       3.000000  120.000000   25.000000             1.000000   
max    15.000000       3.000000  330.000000  100.000000             1.500000   

       Cups per Serving  
count         50.000000  
mean           0.644800  
std            0.547951  
min           -1.000000  
25%            0.670000  
50%            0.750000  
75%            1.000000  
max            1.500000

In [83]:
DFSCereal = DFSCereal[
    ["Name", "Manuf", "Type", "Calories", "Protein", "Sodium", "Potass", "Vitamins"]
]

In [84]:
DFSCereal

Name                        Manuf Type  Calories  \
0                     100%_Bran                      Nabisco    C      70.0   
1             100%_Natural_Bran                  Quaker Oats    C     120.0   
2                      All-Bran                     Kelloggs    C      70.0   
3     All-Bran_with_Extra_Fiber                     Kelloggs    C      50.0   
4                Almond_Delight               Ralston Purina    C     110.0   
5       Apple_Cinnamon_Cheerios                General Mills    C     110.0   
6                   Apple_Jacks                     Kelloggs    C     110.0   
7                       Basic_4                General Mills    C     130.0   
8                     Bran_Chex               Ralston Purina    C       NaN   
9                   Bran_Flakes                         Post    C       NaN   
10                 Cap'n'Crunch                  Quaker Oats    C     120.0   
11                     Cheerios                General Mills    C     110.0   
12        Cinnamon_Toast_Crunch                General Mills    C     120.0   
13                     Clusters                General Mills    C     110.0   
14                  Cocoa_Puffs                General Mills    C     110.0   
15                    Corn_Chex               Ralston Purina    C     110.0   
16                  Corn_Flakes                     Kelloggs    C     100.0   
17                    Corn_Pops                     Kelloggs    C     110.0   
18                Count_Chocula                General Mills    C     110.0   
19           Cracklin'_Oat_Bran                     Kelloggs    C     110.0   
20       Cream_of_Wheat_(Quick)                      Nabisco  NaN     100.0   
21                      Crispix                     Kelloggs    C     110.0   
22       Crispy_Wheat_&_Raisins                General Mills    C     100.0   
23                  Double_Chex               Ralston Purina    C     100.0   
24                  Froot_Loops                     Kelloggs    C     110.0   
25               Frosted_Flakes                     Kelloggs    C     110.0   
26          Frosted_Mini-Wheats                     Kelloggs    C     100.0   
27                Fruitful_Bran                     Kelloggs    C     120.0   
28               Fruity_Pebbles                         Post    C     110.0   
29                 Golden_Crisp                         Post    C     100.0   
30               Golden_Grahams                General Mills    C     110.0   
31            Grape_Nuts_Flakes                         Post    C     100.0   
32                   Grape-Nuts                         Post    C     110.0   
33           Great_Grains_Pecan                         Post    C     120.0   
34             Honey_Graham_Ohs                  Quaker Oats    C     120.0   
35           Honey_Nut_Cheerios                General Mills    C     110.0   
36                   Honey-comb                         Post    C     110.0   
37  Just_Right_Crunchy__Nuggets                     Kelloggs    C     110.0   
38       Just_Right_Fruit_&_Nut                     Kelloggs  NaN     140.0   
39                          Kix                General Mills    C     110.0   
40                         Life                  Quaker Oats    C     100.0   
41                 Lucky_Charms                General Mills    C     110.0   
42                        Maypo  American Home Food Products    H     100.0   
43         Mueslix_Crispy_Blend                     Kelloggs    C     160.0   
44         Multi-Grain_Cheerios                General Mills    C     100.0   
45             Nut&Honey_Crunch                     Kelloggs    C     120.0   
46    Nutri-Grain_Almond-Raisin                     Kelloggs    C     140.0   
47            Nutri-grain_Wheat                     Kelloggs    C      90.0   
48         Oatmeal_Raisin_Crisp                General Mills    C     130.0   
49        Post_Nat._Raisin_Bran                         Post    C     120.0  

# OBTENER LOS VALORES PARA LAS OPERACIONES CON LOS DATOS

In [85]:
""" valores de calories """

calories_values = DFSCereal['Calories'].values
calories_values

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  nan,  nan, 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 110., 100., 110., 100., 110.,
       120., 120., 110., 110., 110., 140., 110., 100., 110., 100., 160.,
       100., 120., 140.,  90., 130., 120.])

In [86]:
""" valores del sodio """

sodium_values = DFSCereal["Sodium"].values
sodium_values

array([130.,  15., 260., 140., 200., 180., 125., 210., 200.,  nan, 220.,
       290., 210., 140., 180., 280., 290.,  90., 180., 140.,  80., 220.,
       140., 190., 125., 200.,   0., 240., 135.,  45., 280., 140., 170.,
        75., 220., 250., 180., 170., 170., 260., 150., 180.,   0., 150.,
       220., 190., 220., 170., 170., 200.])

# Raiz cuadrada con np, pandas y comparar resultados (Columna Calorias)

In [87]:
""" raiz cuadrada con np """

raiz_calories = np.sqrt(calories_values)


""" raiz cuadrada con pandas """


raiz_calories_pd = DFSCereal["Calories"].apply(np.sqrt).values

In [88]:
raiz_calories

array([ 8.36660027, 10.95445115,  8.36660027,  7.07106781, 10.48808848,
       10.48808848, 10.48808848, 11.40175425,         nan,         nan,
       10.95445115, 10.48808848, 10.95445115, 10.48808848, 10.48808848,
       10.48808848, 10.        , 10.48808848, 10.48808848, 10.48808848,
       10.        , 10.48808848, 10.        , 10.        , 10.48808848,
       10.48808848, 10.        , 10.95445115, 10.48808848, 10.        ,
       10.48808848, 10.        , 10.48808848, 10.95445115, 10.95445115,
       10.48808848, 10.48808848, 10.48808848, 11.83215957, 10.48808848,
       10.        , 10.48808848, 10.        , 12.64911064, 10.        ,
       10.95445115, 11.83215957,  9.48683298, 11.40175425, 10.95445115])

In [89]:
raiz_calories_pd

array([ 8.36660027, 10.95445115,  8.36660027,  7.07106781, 10.48808848,
       10.48808848, 10.48808848, 11.40175425,         nan,         nan,
       10.95445115, 10.48808848, 10.95445115, 10.48808848, 10.48808848,
       10.48808848, 10.        , 10.48808848, 10.48808848, 10.48808848,
       10.        , 10.48808848, 10.        , 10.        , 10.48808848,
       10.48808848, 10.        , 10.95445115, 10.48808848, 10.        ,
       10.48808848, 10.        , 10.48808848, 10.95445115, 10.95445115,
       10.48808848, 10.48808848, 10.48808848, 11.83215957, 10.48808848,
       10.        , 10.48808848, 10.        , 12.64911064, 10.        ,
       10.95445115, 11.83215957,  9.48683298, 11.40175425, 10.95445115])

In [90]:
raiz_calories == raiz_calories_pd

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

## Raiz cuadrada con np y pd y comprara los resultados (columna de Sodium)

In [91]:
""" raiz cuadrda con np """


raiz_sodium = np.sqrt(sodium_values)

""" raiz cuadrada con pd """

raiz_sodium_pd = DFSCereal["Sodium"].apply(np.sqrt).values

In [92]:
raiz_sodium

array([11.40175425,  3.87298335, 16.1245155 , 11.83215957, 14.14213562,
       13.41640786, 11.18033989, 14.49137675, 14.14213562,         nan,
       14.83239697, 17.02938637, 14.49137675, 11.83215957, 13.41640786,
       16.73320053, 17.02938637,  9.48683298, 13.41640786, 11.83215957,
        8.94427191, 14.83239697, 11.83215957, 13.78404875, 11.18033989,
       14.14213562,  0.        , 15.49193338, 11.61895004,  6.70820393,
       16.73320053, 11.83215957, 13.03840481,  8.66025404, 14.83239697,
       15.8113883 , 13.41640786, 13.03840481, 13.03840481, 16.1245155 ,
       12.24744871, 13.41640786,  0.        , 12.24744871, 14.83239697,
       13.78404875, 14.83239697, 13.03840481, 13.03840481, 14.14213562])

In [93]:
raiz_sodium_pd

array([11.40175425,  3.87298335, 16.1245155 , 11.83215957, 14.14213562,
       13.41640786, 11.18033989, 14.49137675, 14.14213562,         nan,
       14.83239697, 17.02938637, 14.49137675, 11.83215957, 13.41640786,
       16.73320053, 17.02938637,  9.48683298, 13.41640786, 11.83215957,
        8.94427191, 14.83239697, 11.83215957, 13.78404875, 11.18033989,
       14.14213562,  0.        , 15.49193338, 11.61895004,  6.70820393,
       16.73320053, 11.83215957, 13.03840481,  8.66025404, 14.83239697,
       15.8113883 , 13.41640786, 13.03840481, 13.03840481, 16.1245155 ,
       12.24744871, 13.41640786,  0.        , 12.24744871, 14.83239697,
       13.78404875, 14.83239697, 13.03840481, 13.03840481, 14.14213562])

In [94]:
raiz_sodium == raiz_sodium_pd

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

# Calcular la media con np y con pd (columna de calories)

In [95]:
media_calories_np = np.mean(calories_values)
media_calories_np

nan

In [96]:
media_calories_pd = DFSCereal["Calories"].mean()
media_calories_pd

109.375

In [97]:
""" compracion """
media_calories_np == media_calories_pd

False

# Calcular la media con np y pd (columna de Sodium)

In [98]:
media_sodium_np = np.mean(sodium_values)
media_sodium_np

nan

In [99]:
media_sodium_pd = DFSCereal["Sodium"].mean()
media_sodium_pd

171.83673469387756

In [100]:
""" compracion """
media_sodium_pd == media_sodium_np

False

# Calculo de mediana con np y con pd (columna calories)

In [101]:
mediana_calories_np = np.median(calories_values)
mediana_calories_np

nan

In [102]:
mediana_calories_pd = DFSCereal["Calories"].median()
mediana_calories_pd

110.0

In [103]:
""" comparar resultados """

mediana_calories_np == mediana_calories_pd

False

# calculo de mediana con np y pd (columna sodium)

In [104]:
mediana_sodium_np = np.median(sodium_values)
mediana_sodium_np

nan

In [105]:
mediana_sodium_pd = DFSCereal["Sodium"].median()
mediana_sodium_pd

180.0

In [106]:
mediana_sodium_pd == mediana_sodium_np

False

# Calculo de moda con pd y np (calories)

In [107]:
moda_calories_pd = DFSCereal["Calories"].mode()
moda_calories_pd = moda_calories_pd.values
moda_calories_pd[0]

110.0

In [108]:
valores_unicos, counts = np.unique(DFSCereal["Calories"], return_counts=True)
counter_max = np.argmax(counts)
moda_calories_np = valores_unicos[counter_max]
moda_calories_np

110.0

In [109]:
moda_calories_np == moda_calories_pd[0]

True

# calculo de moda con pd y np de (sodium)

In [110]:
valores_unicos, counts = np.unique(DFSCereal["Sodium"], return_counts=True)
counter_max = np.argmax(counts)
moda_sodium_np = valores_unicos[counter_max]
moda_sodium_np

140.0

In [111]:
moda_sodium_pd = DFSCereal["Sodium"].mode()
moda_sodium_pd = moda_sodium_pd.values
moda_sodium_pd[0]

140.0

In [112]:
moda_sodium_np == moda_sodium_pd[0]

True

# Sutitur valores nulos (por moda o media) en DF original

In [113]:
DFCereal.head()

Name           Manuf Type  Calories  Protein  Fat  \
0                  100%_Bran         Nabisco    C      70.0        4  1.0   
1          100%_Natural_Bran     Quaker Oats    C     120.0        3  5.0   
2                   All-Bran        Kelloggs    C      70.0        4  1.0   
3  All-Bran_with_Extra_Fiber        Kelloggs    C      50.0        4  NaN   
4             Almond_Delight  Ralston Purina    C     110.0        2  2.0   

   Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potass  Vitamins  \
0   130.0           10.0    5.0     6.0            3.0   280.0        25   
1    15.0            2.0    8.0     8.0            3.0   135.0         0   
2   260.0            9.0    7.0     5.0            3.0   320.0        25   
3   140.0           14.0    8.0     NaN            3.0   330.0        25   
4   200.0            1.0   14.0     8.0            3.0     NaN        25   

   Serving Size Weight  Cups per Serving  
0                  1.0              0.33  
1                  1.0             -1.00  
2                  1.0              0.33  
3                  1.0              0.50  
4                  1.0              0.75

False = valores completos, sin valores nulos

True = con valores nulos

In [114]:
DFCereal["Name"].isnull().any()

False

In [115]:
DFCereal["Manuf"].isnull().any()

False

In [116]:
DFCereal["Type"].isnull().any()

True

In [117]:
moda_type = DFCereal["Type"].mode()[0]
moda_type

'C'

In [118]:
DFCereal["Type"] = DFCereal["Type"].fillna(moda_type)
DFCereal["Type"].isnull().any()

False

In [119]:
DFCereal["Calories"].isnull().any()

True

In [120]:
media_calories = DFCereal['Calories'].mean()
media_calories

105.97222222222223

In [121]:
DFCereal["Calories"] = DFCereal["Calories"].fillna(media_calories)
DFCereal["Calories"].isnull().any()

False

In [122]:
DFCereal["Protein"].isnull().any()

False

In [123]:
DFCereal["Fat"].isnull().any()

True

In [124]:
media_fat = DFCereal["Fat"].mean()
media_fat

0.9722222222222222

In [125]:
DFCereal["Fat"] = DFCereal["Fat"].fillna(media_fat)
DFCereal["Fat"].isnull().any()

False

In [126]:
DFCereal["Sodium"].isnull().any()

True

In [127]:
media_sodium = DFCereal["Sodium"].mean()
media_sodium

160.0

In [128]:
DFCereal["Sodium"] = DFCereal["Sodium"].fillna(media_sodium)
DFCereal["Sodium"].isnull().any()

False

In [129]:
DFCereal["Dietary Fiber"].isnull().any()

True

In [130]:
media_duetary = DFCereal["Dietary Fiber"].mean()
media_duetary

2.198550724637681

In [131]:
DFCereal["Dietary Fiber"] = DFCereal["Dietary Fiber"].fillna(media_duetary)
DFCereal["Dietary Fiber"].isnull().any()

False

In [132]:
DFCereal['Carbs'].isnull().any()

True

In [133]:
media_carbs = DFCereal['Carbs'].mean()
media_carbs

15.0

In [134]:
DFCereal["Carbs"] = DFCereal["Carbs"].fillna(media_carbs)
DFCereal["Carbs"].isnull().any()

False

In [135]:
DFCereal["Sugars"].isnull().any()

True

In [136]:
media_sugars = DFCereal['Sugars'].mean()
media_sugars

7.246376811594203

In [137]:
DFCereal["Sugars"] = DFCereal["Sugars"].fillna(media_sugars)
DFCereal["Sugars"].isnull().any()

False

In [138]:
DFCereal.head()

Name           Manuf Type  Calories  Protein  \
0                  100%_Bran         Nabisco    C      70.0        4   
1          100%_Natural_Bran     Quaker Oats    C     120.0        3   
2                   All-Bran        Kelloggs    C      70.0        4   
3  All-Bran_with_Extra_Fiber        Kelloggs    C      50.0        4   
4             Almond_Delight  Ralston Purina    C     110.0        2   

        Fat  Sodium  Dietary Fiber  Carbs    Sugars  Display Shelf  Potass  \
0  1.000000   130.0           10.0    5.0  6.000000            3.0   280.0   
1  5.000000    15.0            2.0    8.0  8.000000            3.0   135.0   
2  1.000000   260.0            9.0    7.0  5.000000            3.0   320.0   
3  0.972222   140.0           14.0    8.0  7.246377            3.0   330.0   
4  2.000000   200.0            1.0   14.0  8.000000            3.0     NaN   

   Vitamins  Serving Size Weight  Cups per Serving  
0        25                  1.0              0.33  
1         0                  1.0             -1.00  
2        25                  1.0              0.33  
3        25                  1.0              0.50  
4        25                  1.0              0.75

In [139]:
DFCereal["Display Shelf"].isnull().any()

True

In [140]:
media_shelf = DFCereal["Display Shelf"].mean()
media_shelf

2.2142857142857144

In [141]:
DFCereal["Display Shelf"] = DFCereal["Display Shelf"].fillna(media_shelf)
DFCereal["Display Shelf"].isnull().any()

False

In [142]:
DFCereal["Potass"].isnull().any()

True

In [144]:
media_potass = DFCereal['Potass'].mean()
media_potass

95.27777777777777

In [145]:
DFCereal["Potass"] = DFCereal["Potass"].fillna(media_potass)
DFCereal["Potass"].isnull().any()

False

In [146]:
DFCereal["Vitamins"].isnull().any()

False

In [147]:
DFCereal["Serving Size Weight"].isnull().any()

False

In [148]:
DFCereal["Cups per Serving"].isnull().any()

False