# Creacion de Arrays


In [284]:
import numpy as np

data1 = [6, 7.5, 8, 0, 1]

<label>Mostrar Lista</label>


In [285]:
data1

[6, 7.5, 8, 0, 1]

# Array 1D


In [286]:
arra1 = np.array(data1)
""" SHOW ARRAY1 """
arra1

array([6. , 7.5, 8. , 0. , 1. ])

<label>Mostrar tipo de dato del array</label>


In [287]:
arra1.dtype

dtype('float64')

<h1>ARRAY 2D</h1>


<label>creacion de una matriz </label>


In [288]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [289]:
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

<label>Creacion de array 2d</label>


In [290]:
array2 = np.array(data2)

<label>mostrar array 2d</label>


In [291]:
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

<label>numero de dimeciones</label>


In [292]:
array2.ndim

2

In [293]:
arra1.ndim

1

<label>dimenciones y elementos</label>


In [294]:
array2.shape

(2, 4)

In [295]:
arra1.shape

(5,)

<label>array de zeros</lable>


In [296]:
array3 = np.zeros((3, 6))

In [297]:
array3

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

<label>Dataos obtenidos de memoria</lable>


In [298]:
arra4 = np.empty((2, 3, 2))

In [299]:
arra4

array([[[1.28005584e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.21190256e-305, 3.72523597e-057]],

       [[2.61998718e+180, 9.90935164e+164],
        [1.31289555e-071, 1.93449756e-076],
        [7.69593388e+169, 7.96132516e-042]]])

<label>Arange : array con un prden consecutivo y rango</lable>


In [300]:
array5 = np.arange(6)

In [301]:
array5

array([0, 1, 2, 3, 4, 5])

<label>Array tipo flotante en serie de dos, con un rango de 10</lable>


In [302]:
array6 = np.arange(1, 10, 2, dtype="float64")

In [303]:
array6

array([1., 3., 5., 7., 9.])

<label>definir tipo de valores</lable>


In [304]:
arr1 = np.array([1, 2, 3], dtype="float64")
arr2 = np.array([1, 2, 3], dtype="int32")

<label>Cambiar tipo de dato del arrelo</lable>


In [305]:
arr3 = arra1.astype(np.int64)

<label>Cambiar tipo de dato en base a lo que prebalesca en otro array</lable>


In [306]:
int_arr4 = np.arange(10)

In [307]:
int_arr4.dtype

dtype('int32')

In [308]:
calibers = np.array([0.22, 0.270, 0.357])
calibers.dtype

dtype('float64')

In [309]:
float_array = int_arr4.astype(calibers.dtype)
float_array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [310]:
arr = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

In [311]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

<label>trae el elemento</lable>


In [312]:
arr[0, 0]

1.0

<label>Cabiar Dato</lable>


In [313]:
arr[1, 2] = 5

In [314]:
arr

array([[1., 2., 3.],
       [4., 5., 5.]])

<label>Copy</lable>


In [315]:
old_arr = arr[0].copy()

In [316]:
old_arr

array([1., 2., 3.])

In [317]:
arr[0]=100
arr

array([[100., 100., 100.],
       [  4.,   5.,   5.]])

In [318]:
old_arr

array([1., 2., 3.])

<label>Operadores boleanoos</lable>


In [319]:
names = np.array(["bob", "benito", "axl"])
names

array(['bob', 'benito', 'axl'], dtype='<U6')

In [320]:
data = np.random.randn(7, 3)
data

array([[ 2.13359121,  1.30219925,  0.03557945],
       [-0.34782066, -0.58558529,  0.13170233],
       [-0.53373497, -1.12185979, -1.48416298],
       [-0.30290452, -0.24436058,  0.61598346],
       [ 1.25118808, -1.09315515, -0.30614167],
       [ 0.31693943, -1.81414188,  0.19737973],
       [ 0.61349848,  2.00971555, -0.16743503]])

In [321]:
names = "benito"
data[names == "benito"]

array([[[ 2.13359121,  1.30219925,  0.03557945],
        [-0.34782066, -0.58558529,  0.13170233],
        [-0.53373497, -1.12185979, -1.48416298],
        [-0.30290452, -0.24436058,  0.61598346],
        [ 1.25118808, -1.09315515, -0.30614167],
        [ 0.31693943, -1.81414188,  0.19737973],
        [ 0.61349848,  2.00971555, -0.16743503]]])

In [322]:
data[names == "benito", 2]

array([[-0.53373497, -1.12185979, -1.48416298]])

In [323]:
names

'benito'

In [324]:
mask = (names == "bob") | (names == "axl")

In [325]:
data[mask]

array([], shape=(0, 7, 3), dtype=float64)

In [326]:
data[data < 0]

array([-0.34782066, -0.58558529, -0.53373497, -1.12185979, -1.48416298,
       -0.30290452, -0.24436058, -1.09315515, -0.30614167, -1.81414188,
       -0.16743503])

In [327]:
data[names != "axl"]

array([[[ 2.13359121,  1.30219925,  0.03557945],
        [-0.34782066, -0.58558529,  0.13170233],
        [-0.53373497, -1.12185979, -1.48416298],
        [-0.30290452, -0.24436058,  0.61598346],
        [ 1.25118808, -1.09315515, -0.30614167],
        [ 0.31693943, -1.81414188,  0.19737973],
        [ 0.61349848,  2.00971555, -0.16743503]]])

In [328]:
data

array([[ 2.13359121,  1.30219925,  0.03557945],
       [-0.34782066, -0.58558529,  0.13170233],
       [-0.53373497, -1.12185979, -1.48416298],
       [-0.30290452, -0.24436058,  0.61598346],
       [ 1.25118808, -1.09315515, -0.30614167],
       [ 0.31693943, -1.81414188,  0.19737973],
       [ 0.61349848,  2.00971555, -0.16743503]])

In [329]:
arrZ = np.arange(15).reshape(3, 5)

In [330]:
arrZ

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [331]:
arrZ.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [332]:
arrX = np.arange(16).reshape((2, 2, 4))

In [333]:
arrX

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [334]:
arrX.transpose(1, 0, 2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [335]:
arrF = np.arange(100)
arrF

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [336]:
arr_sqrt = np.sqrt(arrF)  # raiz cuadrada en todos los elementos
arr_sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ,
       7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
       7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575,
       7.74596669, 7.81024968, 7.87400787, 7.93725393, 8.        ,
       8.06225775, 8.1240384 , 8.18535277, 8.24621125, 8.30662386,
       8.36660027, 8.42614977, 8.48528137, 8.54400375, 8.60232

In [337]:
arr_exp = np.exp(arrF)
arr_exp

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
       7.89629602e+13, 2.14643580e+14, 5.83461743e+14, 1.58601345e+15,
       4.31123155e+15, 1.17191424e+16, 3.18559318e+16, 8.65934004e+16,
       2.35385267e+17, 6.39843494e+17, 1.73927494e+18, 4.72783947e+18,
       1.28516001e+19, 3.49342711e+19, 9.49611942e+19, 2.58131289e+20,
       7.01673591e+20, 1.90734657e+21, 5.18470553e+21, 1.40934908e+22,
       3.83100800e+22, 1.04137594e+23, 2.83075330e+23, 7.69478527e+23,
      

In [338]:
x = np.random.randn(5)
y = np.random.randn(5)

x,y

(array([ 1.13767746, -1.04825797, -0.15728235, -0.57875567,  0.37067717]),
 array([ 0.22512609, -1.44011552,  0.52900498, -0.98476164,  0.47119057]))

In [339]:
arr_max = np.maximum(x, y) # elige el array mayor
arr_max

array([ 1.13767746, -1.04825797,  0.52900498, -0.57875567,  0.47119057])

In [341]:
c = np.array([True, False, False, False, True])
c

array([ True, False, False, False,  True])

In [356]:
d = np.random.randn(4, 4)
d

array([[-0.04397269, -0.22252328, -0.65828459,  1.10978847],
       [-0.08209213,  2.27829134, -1.15736927, -1.74054428],
       [-0.70922101, -0.1702308 , -0.27724603,  0.53036251],
       [ 1.89030427, -0.30048508,  1.14245217,  0.69401773]])

In [359]:
np.where(d > 0.2, -2, d)

array([[-0.04397269, -0.22252328, -0.65828459, -2.        ],
       [-0.08209213, -2.        , -1.15736927, -1.74054428],
       [-0.70922101, -0.1702308 , -0.27724603, -2.        ],
       [-2.        , -0.30048508, -2.        , -2.        ]])

<label>Funciones estadisticas</lable>

In [360]:
z = np.where(c, x, y)
z

array([ 1.13767746, -1.44011552,  0.52900498, -0.98476164,  0.37067717])

In [361]:
vmean = np.mean(z)
vmean

-0.07750350974705242

In [364]:
vmean.sum()

-0.07750350974705242

In [368]:
d.mean(axis=0) #fila

array([ 0.26375461,  0.39626304, -0.23761193,  0.14840611])

In [369]:
d.mean(axis=1)  # columna

array([ 0.04625198, -0.17542858, -0.15658383,  0.85657227])

In [372]:
np.sort(d)

array([[-0.65828459, -0.22252328, -0.04397269,  1.10978847],
       [-1.74054428, -1.15736927, -0.08209213,  2.27829134],
       [-0.70922101, -0.27724603, -0.1702308 ,  0.53036251],
       [-0.30048508,  0.69401773,  1.14245217,  1.89030427]])